services:
  nginx:
    build:
      dockerfile: nginx/Dockerfile
      context: ./
    ports:
    - "80:80"
  goutenberg:
    image: gotenberg/gotenberg:8
    container_name: goutenberg
    ports:
    - "3000:3000"